[connections.supabase]
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbWduY2p6bWtnYXZrbGlweXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDAxMzc1OTUsImV4cCI6MjAxNTcxMzU5NX0.u_0xe0MRxffwRPw9mSkc4uQKXIZjsPxDVWumqDG-I4E"
SUPABASE_URL = "https://ulmgncjzmkgavklipypl.supabase.co"